name: Planner - Build and deploy client as an Azure Static Web App

on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

env:
  SERVER_ENDPOINT: https://planner-dev-1.azurewebsites.net

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.20.0

      - name: Set github registry token
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

      - name: Install workspace dependencies.
        run: pnpm install

      - name: Build complete project.
        run: pnpm build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_SAND_03E161D03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/packages/client/dist" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
