name: Planner - Build and deploy server package as an Azure App Service.

on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Install workspace dependencies.
        run: pnpm install

      - name: Build complete project.
        run: pnpm build

      - name: Change workspace deps to file deps for npm compatibility.
        run: pnpm workspace-to-file-deps

      - name: run npm install inside the server folder.
        working-directory: packages/server
        run: |
          pnpm rimraf **/node_modules
          npm install --omit=dev

      - name: Zip all files for upload between jobs
        working-directory: packages/server
        run: zip -x *.git* -r --symlinks nest.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.1
        with:
          name: node-app
          path: packages/server/nest.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3.0.1
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2.2.5
        with:
          app-name: "planner-dev-1"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F55183AE9F2845949AE6B34BDE823AFC }}
          package: nest.zip

      - name: Delete zip file
        run: rm nest.zip
