name: Publish package-toolbox

on:
   # Runs on pushes targeting the default branch
   push:
      paths:
       - 'packages/package-toolbox/**'
      branches: ["publish"]

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          registry-url: https://registry.npmjs.org/

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest

      - name: Install dependencies.
        run: pnpm install

      - name: Build complete project.
        run: |
         cd packages/package-toolbox
         pnpm build

      - name: Change package version.
        run: |
         cd packages/package-toolbox
         pnpm increment-version

      - name: Merge tsconfig.
        run: |
         cd packages/package-toolbox
         pnpm merge-tsconfig

      - name: Publish package.
        run: |
         cd packages/package-toolbox
         pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}