name: Publish Lit-Aegis

on:
   push:
      paths:
         - 'packages/lit/lit-aegis/**'
      branches: ["publish"]

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
         node-version: 22
         registry-url: https://registry.npmjs.org/

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
         version: latest

      - name: Install workspace dependencies.
        run: pnpm install

      - name: Build all requires dependencies and project.
        run: |
         cd packages/package-toolbox && pnpm build
         cd ../core                  && pnpm build
         cd ../reflect-metadata      && pnpm build
         cd ../lit/lit-aegis         && pnpm build

      - name: Change package version and publish package
        run: |
         cd packages/lit/lit-aegis && pnpm increment-version
         pnpm publish --access public --no-git-checks
        env:
         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
