name: Publish monaco editor component

on:
  push:
    paths:
      - "components/editor/**"
    branches: ["publish"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest

      - name: Install workspace dependencies.
        run: pnpm install

      - name: Build dependencies, project and publish package.
        run: pnpm release @roenlie/monaco-editor-wc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
