name: Sync lit-jsx to standalone repo

on:
  push:
    branches: [main]
    paths: ['packages/lit-jsx/**']
  workflow_dispatch:

jobs:
  sync-subtree:
    uses: roenlie/github-workflows/.github/workflows/subtree-sync.yml@main
    with:
      package-path: packages/lit-jsx
      target-repo: RoenLie/jsx-lit
    secrets:
      sync-token: ${{ secrets.SUBTREE_SYNC }}
